[project]
name = "wazuh-agent"
version = "0.1.0"
description = "Juju charm for the Wazuh Agent"
requires-python = ">=3.10"
dependencies = [
    "ops>=2.0,<3.0",
]

[project.optional-dependencies]
dev = [
    "coverage[toml]",
    "pytest",
    "pytest-operator",
    "ruff",
]

[tool.ruff]
line-length = 99
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli_level = "INFO"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true